#DEV environment

app:
  message:
  This is property file for the ${spring.application.name} specific for DEV Environment

spring:
  datasource:
  driver-class-name: org.h2.Driver
  url: jbdc:h2:mem:db;DB_CLOSE_DELAY=-1
  username: sa
  password: sa